// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfadaH5nB5GIfk0119tjYmBkDiydycJ9k',
    appId: '1:39856083635:web:ab179cde262b46d69296c6',
    messagingSenderId: '39856083635',
    projectId: 'evently-6e98c',
    authDomain: 'evently-6e98c.firebaseapp.com',
    storageBucket: 'evently-6e98c.firebasestorage.app',
    measurementId: 'G-2MVQKJ7SD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ynf-z-h7Vzvu0lDN64z1bLIKcFpJfvI',
    appId: '1:39856083635:android:139e30f5680091f19296c6',
    messagingSenderId: '39856083635',
    projectId: 'evently-6e98c',
    storageBucket: 'evently-6e98c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiSz1X2bMFUzydY4pFCPlT_oOLrcNnKYM',
    appId: '1:39856083635:ios:ea91416996419b869296c6',
    messagingSenderId: '39856083635',
    projectId: 'evently-6e98c',
    storageBucket: 'evently-6e98c.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiSz1X2bMFUzydY4pFCPlT_oOLrcNnKYM',
    appId: '1:39856083635:ios:ea91416996419b869296c6',
    messagingSenderId: '39856083635',
    projectId: 'evently-6e98c',
    storageBucket: 'evently-6e98c.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfadaH5nB5GIfk0119tjYmBkDiydycJ9k',
    appId: '1:39856083635:web:a5cc13f3f1674be09296c6',
    messagingSenderId: '39856083635',
    projectId: 'evently-6e98c',
    authDomain: 'evently-6e98c.firebaseapp.com',
    storageBucket: 'evently-6e98c.firebasestorage.app',
    measurementId: 'G-DYPBRCYLYL',
  );
}
